apiVersion: "serving.kubeflow.org/v1beta1"
kind: "InferenceService"
metadata:
  name: "sklearn-irisv2"
spec:
  predictor:
    sklearn:
      storageUri: "file:///home/jovyan/model.joblib"
      protocolVersion: "v2"
      image: dsimages/sklearn_iris_imagev2
